fix: bug fixes related to logic and rendering #6
Dave136/vue-email pull request #7
Opened 2023-07-08 01:22 UTC by Flowko

### fixes:
- cant use dynamic components inside of tailwind
- cant style button/heading

### updates:
- cleaning code and using modern logic

@Dave136 im looking forward to seeing this get merged as it fixes a major bug related to tailwind, let me know your views on this, and i have some ideas on improving this library as i see it unique and needed in the vue eco system

2023-07-08 03:55 UTC, Dave136 commented
@Flowko Thank you for taking the time to help improve the project! Your assistance is appreciated. I will review the changes and leave a comment if necessary.

Feel free to submit requests for new features or proposals to improve the library, so that we can discuss them in the pull request.

2023-07-09 01:39 UTC, Dave136 requested changes
Good job! But there's small things to improve, I'll waiting for your response.

2023-07-09 01:39 UTC, Dave136 commented on packages/vue-email/src/components/e-button.vue
> -    v-bind="$props"
Binding props is the way to pass the n element attributes. I thing that it's important to keep it.

2023-07-09 01:39 UTC, Dave136 commented on packages/vue-email/src/components/e-button.vue
> -    :target="target"
Usually the email buttons redirect to a blank page loading the target, both attributes must be required, what do you think about it?

2023-07-09 01:39 UTC, Dave136 commented on packages/vue-email/src/components/e-button.vue
>    return {
Passing the `style` prop gives the user the ability to add custom styles to the component, particularly when they don't want to use Tailwind classes. What's your point in this case?

2023-07-09 01:39 UTC, Dave136 commented on packages/vue-email/src/components/e-heading.vue
>    <component
Binding, like in the previous case, is important because it allows the user to utilize the native tag props.

2023-07-09 01:39 UTC, Dave136 commented on packages/vue-email/src/components/e-heading.vue
> +        ml,
Similar to the previous example, passing the `style` prop provides users with the opportunity to add custom styles when they choose not to utilize Tailwind classes. What do you think about this?

2023-07-09 01:39 UTC, Dave136 commented on packages/vue-email/src/components/e-html.vue
> +  <slot />
Indenting the <slot /> tag correctly between HTML tags is important to maintain clean code and adhere to best practices. It also helps remove any unnecessary spaces in the following line.

2023-07-09 01:39 UTC, Dave136 commented on playground/src/examples/twitch-reset-password.vue
> +  <e-tailwind>
I'm not sure if using Tailwind as the root component would be convenient, as `e-head` and `e-preview` don't require styles. Tell me whats is your point?

2023-07-09 01:39 UTC, Dave136 commented on playground/src/examples/with-tailwind.vue
> +  <e-tailwind>
Here it's the same case that i commented above

2023-07-09 10:51 UTC, Flowko commented
i'll response here, i think its better.


---------
so about binding props, based on these [docs](https://vuejs.org/guide/components/attrs.html) you dont have to do that anymore, as any props passed to the components like style/classes/extra props, will be merged together, so for styles, you dont have to, as i did some testing for the `button` and `heading` element, and it seems to be the case, it gets the styles correctly and adds them to the main style of the element with no problem, you could test it locally to be sure, for example:
with the new button:

| ![image](https://github.com/Dave136/vue-email/assets/35883748/0d95fb2a-be3b-4c13-b7b4-420c1227f4e4) | ![image](https://github.com/Dave136/vue-email/assets/35883748/5280d4bd-fcea-4137-9aa7-9bdaa129193a) | ![image](https://github.com/Dave136/vue-email/assets/35883748/4d730e03-1a2c-45d1-9820-f1396774dfc6) |
|-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|

---------

> I'm not sure if using Tailwind as the root component would be convenient, as e-head and e-preview don't require styles. Tell me whats is your point?

this is need because of the media styles, so if we have responsive styles inside of our tailwind layout, we will convert those to be added inside of the head tag, as that where it will hold the styles, plus the `react-email` library is using it already: [ref](https://github.com/resendlabs/react-email/blob/main/packages/tailwind/src/tailwind.tsx)

-----

> Indenting the tag correctly between HTML tags is important to maintain clean code and adhere to best practices. It also helps remove any unnecessary spaces in the following line.

my bad, its just my vscode auto formatter didnt work correctly, ill fix that

-----

> Usually the email buttons redirect to a blank page loading the target, both attributes must be required, what do you think about it?
i actually missed these, ill add them back to the props field

<br/>
<br/>

hopefully this answers all your questions

2023-07-09 18:40 UTC, Dave136 commented
@Flowko Thank you for adding support to the project! 💪🏼

> this is need because of the media styles, so if we have responsive styles inside of our tailwind layout, we will convert those to be added inside of the head tag, as that where it will hold the styles, plus the react-email library is using it already: [ref](https://github.com/resendlabs/react-email/blob/main/packages/tailwind/src/tailwind.tsx)

You are correct, but the idea was to only wrap the affected components with the TailwindCSS class. What do you think?

2023-07-09 19:11 UTC, Flowko commented
i believe its best to include the styles in a head style tag, at least the media ones, the thing is, it doesnt just add the media tags to the style element, so for example:

you have a component:
```html

<e-section class="mt-[32px] md:mt-[60px]">
            <e-img :src="VercelLogo" width="40" height="37" alt="Vercel" class="my-0 mx-auto" />
          </e-section>

```

what this will be converted to is:

```html
<table align="center" width="100%" data-id="__vue-email-section" border="0" cellpadding="0" cellspacing="0" role="presentation" class="md_mt_60px_" style="margin-top: 32px;">
  <tbody>
    <tr>
      <td>
        <img src="/src/assets/vercel-logo.png" width="40" height="37" alt="Vercel" data-id="__vue-email-img" style="margin: 0px auto; display: block; outline: none; border: none; text-decoration: none;">
      </td>
    </tr>
  </tbody>
</table>
```

you see the `md_mt_60px_` class, this will be linked with the style element that gets added:

```
<style>@media(min-width:768px){.md_mt_50px_{margin-top: 50px !important;}.md_mt_60px_{margin-top: 60px !important;}}</style>
```

what this does it just makes it easier to have all the styles in one place for easiness and even if they wanna update a specific value later on, they can easily do so if they want, and to be actually using the style tag rather than just cramp everything in the element styles.

i just found an issue with the head element, ill fix it when i have some time, its just not adding to the main head element, rather creating a new head element and adding the style to, good that we checked this haha

2023-07-09 20:09 UTC, Dave136 commented
@Flowko I was trying to see your changes locally, but when I opened the playground, the components that use TailwindCSS threw an error and didn't render.

![image](https://github.com/Dave136/vue-email/assets/49698182/e6af5de1-bec3-4f90-a44a-5b77f279a979)

2023-07-09 22:36 UTC, Flowko commented
@Dave136 did u like change something in the template? 
Stupid question, but did u do a npm run build on the vue-email package ?

2023-07-09 22:43 UTC, Flowko commented
tested on firefox as well!
![image](https://github.com/Dave136/vue-email/assets/35883748/99250d6a-7086-4df2-a966-a3746e3e9ec0)

2023-07-09 22:55 UTC, Dave136 commented
Sorry, it turned out to be a local error with the cache.

There is a conflict with `docs/usage.md`, could you please fix it?

2023-07-09 23:05 UTC, Flowko commented
done

2023-07-09 23:28 UTC, Dave136 commented
Sure man! You can found me as `dave136`

2023-07-09 23:29 UTC, merged