refactor(all): improved setup
Dave136/vue-email pull request #9
Opened 2023-07-11 11:41 UTC by Flowko

major changes to the code base.

- [ ] Added Tests
- [ ] Easy Nuxt/Vue setup
- [ ] Github Workflow
- [ ] Easy Publish Setup
- [ ] Improved Demo
- [ ] Examples

2023-07-14 04:39 UTC, Dave136 requested changes
Great job! 💪🏼 

Thanks for this excellent support.

But, there's a changes to do, please, check it out!

2023-07-14 04:39 UTC, Dave136 commented on demo/emails/yelp-recent-login.vue
> +const props = defineProps({
Here we can define the props using typescript features? Just to give more examples using ts.

2023-07-14 04:39 UTC, Dave136 commented on demo/pages/index.vue
> +<script setup lang="ts">
`lang="ts"` can be removed!

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Body.vue
> +<script lang="ts" setup>
`<script>` tag is empty, can we remove it?

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Column.vue
> +<script lang="ts" setup></script>
Can we remove it?

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Container.vue
> +<script lang="ts" setup></script>
Can we remove it?

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Head.vue
> +
There is a no needed space here... It can be removed

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Head.vue
> +<script lang="ts" setup></script>
Can we remove it?

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Hr.vue
> +<script lang="ts">
`lang="ts"` is not needed in this context

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Hr.vue
> +<script lang="ts" setup></script>
Can we remove this line?

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Html.vue
> +<script lang="ts">
`lang` is not needed here.

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Html.vue
> +</script>
Can we have a space between `script` and `template` tags?

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Img.vue
> +<script lang="ts">
`lang` is not needed

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Img.vue
> +</script>
Can we have a space between `script` and `template` tags?

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Img.vue
> +<script lang="ts" setup>
`lang` is not needed here, we are not using ts here

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Link.vue
> +<script lang="ts">
Remove `lang`, please.

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Link.vue
> +</script>
Here spacing between tags, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Link.vue
> +<script lang="ts" setup>
`lang` is not needed here.

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Preview.vue
> +<script lang="ts">
Remove `lang`, please.

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Preview.vue
> +</script>
Space between tags, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Preview.vue
>  <script lang="ts" setup>
Remove `lang` if ts is not in use.

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Row.vue
> +<script lang="ts">
Remove `lang`

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Row.vue
> +</script>
Space between tags

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Row.vue
> +<script lang="ts" setup></script>
This line is not needed

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Section.vue
> +<script lang="ts">
Same case, remove `lang`, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Section.vue
> +</script>
Add space between tags.

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Section.vue
> +<script lang="ts" setup></script>
This line is not needed here.

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Tailwind.vue
> +<script lang="ts">
Remove `lang` here

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Text.vue
> +<script lang="ts">
Remove `lang`, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/Text.vue
> +</script>
Space between tags, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Body.spec.ts
> +import { compile, h } from 'vue'
Here we can use import order rules

- 3th party libs
- custom
- types

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Button.spec.ts
> +import { h } from 'vue'
Importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Column.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Container.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Font.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Head.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Heading.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Hr.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Html.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Img.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Link.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Row.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Section.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Tailwind.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-14 04:39 UTC, Dave136 commented on packages/vue-email/src/components/__tests__/Text.spec.ts
> +import { h } from 'vue'
importation order, please

2023-07-15 19:05 UTC, Flowko commented
i resolved some of the comment, but for stuff like remove lang='ts' from the script tag, i left, as i get an error when building, 
`[@vue/compiler-sfc] <script> and <script setup> must have the same language type.` and i dont see an issue if its even there, as its not something that affects the end user, as everything gets compiled

2023-07-16 15:22 UTC, Dave136 approved these changes
Good job! 🚀

2023-07-16 15:23 UTC, merged